=== ptitguigui/M1/tp3/exo2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Tous les types -->
<xs:complexType name="typeStock">
	<xs:sequence>
		<xs:element name="occases"  type="typeOccases" minOccurs="1" />
		<xs:element name="neufs" type="typeNeufs" minOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="nom" type="xs:string"/>
</xs:complexType>

<xs:complexType name="typeOccases">	
	<xs:sequence>	
		<xs:element name="item"  type="typeItemOccaz" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="typeNeufs">
	<xs:sequence>
		<xs:element name="item"  type="typeItemNeuf" minOccurs="1" maxOccurs="unbounded" />
	</xs:sequence>
</xs:complexType>


<xs:complexType name="typeItemNeuf">
	<xs:sequence>
		<xs:element name="marque" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="modele" type="xs:string" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="prix" type="xs:integer"/>
</xs:complexType>


<xs:complexType name="typeItemOccaz">
	<xs:complexContent>
		<xs:extension base="typeItemNeuf">		
			<xs:sequence>
					<xs:element name="annee" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>

<!--Tous les elements -->
<xs:element name="stock" type="typeStock"/>

</xs:schema>

=== ptitguigui/M1/M1S2/LABD/tp3/labd-3/okaz.xml
<?xml version="1.0" encoding="UTF-8"?>

<stock xs:noNamespaceSchemaLocation="../exo2.xsd" 
	  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
	  nom="OccazEtNeufs">
    <occases>
        <item prix="2000">
            <marque>Renault</marque>
            <modele>Clio II</modele>
            <annee>1998</annee>
        </item>
        <item prix="10000">
            <marque>BMW</marque>
            <modele>Serie 5</modele>
            <annee>2002</annee>
        </item>
        <item prix="4800">
            <marque>Peugeot</marque>
            <modele>307</modele>
            <annee>2001</annee>
        </item>
    </occases>
    <neufs>
        <item prix="18000">
            <marque>Renault</marque>
            <modele>Clio IV</modele>
        </item>
        <item prix="29900">
            <marque>BMW</marque>
            <modele>Serie 5</modele>
        </item>
    </neufs>
</stock>
